micronaut:
  application:
    name: orangeMarketplace
datasources:
  default:
    url: ${JDBC_URL:`jdbc:postgresql://localhost:5432/orangestackdb`}
    driverClassName: org.postgresql.Driver
    username: ${JDBC_USER:postgres}
    password: ${JDBC_PASSWORD:mysecretpassword}
    schema-generate: CREATE_DROP
    dialect: POSTGRES
jpa.default.properties.hibernate.hbm2ddl.auto: update
