micronaut:
  application:
    name: orangeMarketplace

datasources:
  default:
  url: ${JDBC_URL:`jdbc:postgresql://postgres:5432/orangestackdb`}
  driverClassName: org.postgresql.Driver
  username: ${JDBC_USER:postgres}
  password: ${JDBC_PASSWORD:mysecretpassword}
  schema-generate: CREATE_DROP
  dialect: POSTGRES
  connectionTimeout: 2000
jpa:
  default:
  entity-scan:
  packages: 'com.itau.orange.marketplace.entity'
  properties:
  hibernate:
  hbm2ddl:
  auto: update